name: "🐞 Bug report"
description: "Report a reproducible problem so we can fix it"
title: "bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a bug report!
        Please complete all required fields to help us reproduce the issue.

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight checklist
      options:
        - label: I searched existing issues and didn’t find a duplicate
          required: true
        - label: I read the Contribution Guidelines
          required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected area
      options:
        - Web (Next.js)
        - API (Express/Socket.IO)
        - Widget
        - Infra / Docker
        - Docs
      multiple: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: Clear and concise description of the bug
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Provide exact steps so we can reproduce
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs/output
      description: Paste any logs or errors. Use code blocks when possible.
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Drag and drop images here if applicable

  - type: textarea
    id: env
    attributes:
      label: Environment
      placeholder: |
        Commit/Version: <git sha or tag>
        OS: macOS 14
        Browser: Chrome 127
        Node: 18.x
        Docker Desktop: 4.x

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      placeholder: Any other context or links
