name: "📌 General Issue"
description: "Report a bug or request a feature"
title: "[Type]: "
labels: []
body:
  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      description: Select the type of issue
      options:
        - Bug Report 🐞
        - Feature Request 🚀
    validations:
      required: true

  # Feature request section
  - type: markdown
    attributes:
      value: "### 🛠 Feature Request Section (fill only if you selected Feature Request)"
  - type: input
    id: feature_what
    attributes:
      label: What Feature?
      placeholder: "Example: Add dark mode to chat widget"
  - type: textarea
    id: feature_why
    attributes:
      label: Why is this needed?
      placeholder: "Explain the problem it solves or value it adds"
  - type: textarea
    id: feature_behavior
    attributes:
      label: Expected Behavior
      placeholder: "Describe how it should work"

  # Bug report section
  - type: markdown
    attributes:
      value: "### 🐞 Bug Report Section (fill only if you selected Bug Report)"
  - type: textarea
    id: bug_problem
    attributes:
      label: Problem
      placeholder: "Describe the problem clearly"
  - type: textarea
    id: bug_screenshots
    attributes:
      label: Screenshots
      placeholder: "Attach screenshots or paste image links"
  - type: textarea
    id: bug_behavior
    attributes:
      label: Current Behavior
      placeholder: "Describe what happens now"
  - type: textarea
    id: bug_expected
    attributes:
      label: Expected Behavior
      placeholder: "Describe what should happen instead"
  - type: textarea
    id: bug_solution
    attributes:
      label: Possible Solution (Optional)
      placeholder: "If you have any ideas to fix this"
  - type: textarea
    id: bug_environment
    attributes:
      label: Environment
      placeholder: "Browser: Chrome 115, OS: macOS 13..."
